# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-13 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banners',
        ),
        migrations.RemoveField(
            model_name='carouselslide',
            name='carousel',
        ),
        migrations.RemoveField(
            model_name='page',
            name='carousel',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='back_color',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='back_resize',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='citys',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='link_1_file',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='link_1_link',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='link_1_text',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='link_1_title',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='link_2_file',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='link_2_link',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='link_2_text',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='link_2_title',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='link_3_file',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='link_3_link',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='link_3_text',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='link_3_title',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='main_back_color',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='shops',
        ),
        migrations.AlterField(
            model_name='setting',
            name='email1',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Телефонный номер'),
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.DeleteModel(
            name='CarouselSlide',
        ),
    ]
