# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-20 12:41
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180613_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='new_flag',
        ),
        migrations.RemoveField(
            model_name='item',
            name='offer_text1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='offer_text2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='offer_text_price',
        ),
        migrations.AlterField(
            model_name='category',
            name='file',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='category', verbose_name='Фото для категории 250X250'),
        ),
        migrations.AlterField(
            model_name='item',
            name='file',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='category', verbose_name='Фото для категории 250X250'),
        ),
    ]
