# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-20 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180620_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='offer_name2',
        ),
        migrations.AlterField(
            model_name='item',
            name='offer_name1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Наименование'),
        ),
    ]
