# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-20 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180620_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='offer_name2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Наименование модель'),
        ),
    ]
