# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-20 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180620_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='min_lot',
        ),
        migrations.RemoveField(
            model_name='item',
            name='min_offer',
        ),
    ]
