# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-20 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180620_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='offer_text_cost',
        ),
        migrations.AddField(
            model_name='item',
            name='price_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
