# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-22 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_item_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brands',
            old_name='phone_number',
            new_name='title',
        ),
    ]
