# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-27 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180622_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bik',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='kpp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ks',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='orgn',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rs',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=1000, verbose_name='ФИО'),
        ),
    ]
