# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-26 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_item_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='id1c',
            field=models.IntegerField(default=0, verbose_name='1C - ID'),
        ),
    ]
