# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-31 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20180726_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code1c',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Код базы'),
        ),
    ]
