# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-31 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_category_code1c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='code1c',
        ),
    ]
