# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-07 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20180801_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_pay',
            field=models.TextField(default='', verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_diliver',
            field=models.TextField(default='', verbose_name='Тип доставки'),
        ),
    ]
