# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-07 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20180807_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(default='', verbose_name='Статус заказа'),
        ),
    ]
