# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-07 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20180807_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.TextField(default='', verbose_name='ФИО заказчика'),
        ),
    ]
