# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-21 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20180807_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Оформлен'), (2, 'Разрешена оплата'), (3, 'Оплачен'), (4, 'Отправлен'), (5, 'Завершен')], default=1),
        ),
    ]
