# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-10 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_keywords',
            field=models.TextField(blank=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.TextField(default='', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='meta_keywords',
            field=models.TextField(blank=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(default='', verbose_name='Название'),
        ),
    ]
